### ISSUE TITLE
Implementação endpoint para verificação do EMAIL existente (API)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#104]
### **Contexto**
Necessário realizar implementação de um endpoint para realizar a validação pra saber se o usuário já está cadastrado com o EMAIL informado por parâmetro.

**Comment by victorMagalhaesPacheco** [comment]
Exemplo: 
**Requisição:** 
```http
GET /api/user/email-cadastrado/EMAIL_A_CONSULTAR_AQUI HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: BASE_URL_API
```

**Resposta caso CPF já exista no ID SAÚDE:**
```json
{
  "email_existe": true,
  "mensagem": "EMAIL já cadastrado no ID Saúde"
}
```

**Resposta caso EMAIL não exista no ID SAÚDE:**
```json
{
  "email_existe": false
}
```

**Resposta caso EMAIL seja inválido:**
```json
{
  "sucesso": true,
  "mensagem": {
    "email": [
      "O campo email deve ser um endereço de e-mail válido."
    ]
  }
}
```

**Comment by victorMagalhaesPacheco** [comment]
> Exemplo:
> **Requisição:**
> 
> ```httpspec
> GET /api/user/email-cadastrado/EMAIL_A_CONSULTAR_AQUI HTTP/1.1
> Content-Type: application/x-www-form-urlencoded
> Host: BASE_URL_API
> ```
> 
> **Resposta caso CPF já exista no ID SAÚDE:**
> 
> ```json
> {
>   "email_existe": true,
>   "mensagem": "EMAIL já cadastrado no ID Saúde"
> }
> ```
> 
> **Resposta caso EMAIL não exista no ID SAÚDE:**
> 
> ```json
> {
>   "email_existe": false
> }
> ```
> 
> **Resposta caso EMAIL seja inválido:**
> 
> ```json
> {
>   "sucesso": true,
>   "mensagem": {
>     "email": [
>       "O campo email deve ser um endereço de e-mail válido."
>     ]
>   }
> }
> ```

@nicoledbianchin

**Comment by Laysacunha** [comment]
Issue vai ser fechada porque funcionalidade já foi implementada.
