### ISSUE TITLE
Modelo entidade relacionamento iSUS

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#106]
![mer-isus](https://user-images.githubusercontent.com/3487411/95585338-78ab1100-0a15-11eb-87e7-d274e90b25ed.png)

**Comment by victorMagalhaesPacheco** [comment]
@ItaloRod e @ruigmoreno aqui é o modelo da API, importante para ter uma visão geral.

**Comment by Laysacunha** [comment]
[MER Atualizado](https://drive.google.com/file/d/1evWMdRH668oQtyRkkvSmfdlnftAJcCSM/view?usp=sharing)
Essa versão inclui tabelas do qualiquiz.
