### ISSUE TITLE
Implementar endpoint para remover usuário

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#111]
### **Contexto**
Necessário realizar implementação de um endpoint para realizar a remoção do usuário. Para estarmos alinhados com a nova lei de proteção de dados é necessário que essa funcionalidade sejam implementada.

**Comment by victorMagalhaesPacheco** [comment]
Exemplo: 
**Request:** 
```http
Verbo DELETE /api/user HTTP/1.1
Content-Type: application/json
Host: BASE_URL_API
Header
Authorization: Bearer TOKEN_AQUI
Body: 
{
	"senha":"SENHA_USUARIO"
}
```

**Resposta ok:**
```json
{
  "sucesso": true,
  "mensagem": "Usuário excluído com sucesso"
}
```

**Resposta erro senha inválida:** HTTP - 401
```json
{
  "sucesso": false,
  "mensagem": "Senha inválida"
}
```

**Comment by aninhasantos** [comment]
Não é necessário mais enviar a senha para realizar a exclusão do ID Saude. @victorMagalhaesPacheco
