### ISSUE TITLE
Criar recurso para ser possível retornar pontuação de usuária que realizou o quiz

### ISSUE THREAD

**Issue by aninhasantos** [EscolaDeSaudePublica/isus-api#125]
## **Objetivo**

**Como** pessoa desenvolvedora  
**Quero** retornar a pontuação de um determinado quiz da usuária logada
**Para** obter sua nota do teste realizado

## **Contexto**

Como o quiz do SUS está disponível no iSUS, ao clicar no ícone de qualiquiz no app iSUS, é chamado o endpoint do qualiquiz; nisso, a API deverá validar se a usuária já realizou o quiz realmente. Caso ainda não tenha realizado, será necessário buscar as questões do quiz; caso contrário, caso o quiz já tenha sido realizado, deverá buscar a pontuação do quiz para exibir para a usuária posteriormente. 

## **Escopo**

- [ ] Adicionar o token no cabeçalho da rota do endereço `/qualiquiz/quiz/{cod_quiz}` 
- [ ] Validar se a usuária já realizou o quiz
- [ ] Buscar as questões do quiz, caso ainda não tenha realizado
- [ ] Buscar sua pontuação final, caso já tenha realizado

## **Fora do Escopo**

- A parte de visualização dessa pontuação pelo qualiquiz ou pelo iSUS não será tratada nessa atividade, visto que ainda é necessário definir o protótipo e a experiência desse retorno. Nessa atividade, criaremos o recurso desse feedback pela API. 

## **Critérios de Aceitação**

- [ ] 1. consulta valida para usuária que ainda não realizou o quiz  
**Dado** uma requisição GET para o Qualiquiz com um código válido de uma usuária que ainda não tenha realizado o teste 
**Quando** é disparada essa chamada 
**então** deve ser retornado uma resposta com status `200`, um objeto json contendo os dados do quiz: quiz, questões, opções

- [ ] 2. consulta valida para usuária que já realizou o quiz
**Dado** uma requisição GET para o Qualiquiz com um código válido de uma usuária que tenha realizado o teste 
**Quando** é disparada essa chamada 
**então** deve ser retornado uma resposta com status `200`, um objeto json contendo a pontuação do quiz: nome e/ou ID do quiz (sem as questões), pontuação

- [ ] 3. consulta com cod_quiz inválido  
**Dado** uma requisição GET para o Qualiquiz com um código inválido de quiz
**Quando** é disparada essa chamada 
**então** deve ser retornado uma resposta com status `404`, uma mensagem no body informando que o código enviado é inválido

- [ ] 4. consulta sem cod_quiz  
**Dado** uma requisição GET para o Qualiquiz sem um código de quiz
**Quando** é disparada essa chamada 
**então** deve ser retornado uma resposta com status code `400` referente a informação obrigatória ausente, uma mensagem no body informando que o código de quiz é obrigatório

- [ ] 5. consulta com cod_quiz inválido  
**Dado** uma requisição GET para o Qualiquiz com um código de quiz contendo caracteres não numéricos
**Quando** é disparada essa chamada 
**então** deve ser retornado uma resposta com status `400`, uma mensagem no body informando que o código enviado é inválido

**Comment by Laysacunha** [comment]
Hoje o qualiquiz já trabalha com múltiplos quizzes e já é possível revisar uma tentativa e verificar pontuação atingida. Logo, funcionalidade ok e issue será fechada.
