### ISSUE TITLE
Implementar devolução de respostas certas e erradas durante teste do Qualiquiz

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-api#129]
## **Objetivo**

**Como** usuária do iSUS que está realizando o Qualiquiz  
**Quero** saber se a resposta escolhida está certa ou errada, e porque 
**Para** entender o gabarito e autoavaliar meu desempenho

## **Contexto**

- O Qualiquiz consiste num teste direcionado para determinados perfis e expertises de profissionais de saúde, com o intuito de avaliar suas competências nas áreas de atuação e apoiar sua aprendizagem. Assim, é importante que a usuária possa receber um feedback sobre a questão respondida, se está correta, e se não está, apresentar a correta com sua respectiva explicação.

## **UX**

- [ ] Estruturar o fluxo do Qualiquiz, a jornada do usuário, considerando essa experiência de feedback

## **Escopo**

- [ ] Implementar retorno com respostas

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

# Observações

ex: Prototipo

**Comment by jessica-salmazzo** [comment]
Ainda não detalhamos essa estória porque estamos aguardando a definição se vamos prosseguir utilizando a estrutura do Qualiquiz ou se migraremos para a estrutura do Moodle para lidar com os quiz a fim de evitar retrabalho da equipe e retrabalho de escrita.

**Comment by chicaothiago** [comment]
https://github.com/EscolaDeSaudePublica/isus-api/issues/125

Esta atividade foi cancelada, o retorno das respostas ocorrerá somente ao concluir o quiz. 
Enquanto nesta atividade tinha-se a ideia de retornar após a seleção de uma resposta. 
Foi abandonada esta possibilidade em uma conversa que houve com o time de UX. O que ocasionou na priorização da atividade #125
