### ISSUE TITLE
Criar rota para Dúvidas sobre o Elmo no Fale Conosco

### ISSUE THREAD

**Issue by Clarisse1983** [EscolaDeSaudePublica/isus-api#142]
## **Objetivo**

**Como** pessoa desenvolvedora do iSUS app
**Quero** criar uma rota para as dúvidas sobre o Elmo
**Para** devolver respostas às usuárias solicitantes

## **Contexto**

Estamos implementando a opção 'Dúvidas sobre o Elmo' nos tipos de ocorrência (drop down) no Fale Conosco e precisamos criar a rota para essa implementação na api.

## **Escopo**

- [x] Um email deve ser enviado quando a usuária submeter o feedback em Fale Conosco, item 'Duvidas sobre o Elmo'. O assunto deverá ser ISUS APP - DÚVIDAS SOBRE O ELMO. DD/MM/AAAA HH:MM:SS e o remetente o email informado pelo usuário

## **Critérios de aceitação:**

- [x] **Dado que** preenchi todos os dados necessário para submeter uma 'Dúvida sobre o Elmo'
**Quando** eu submeter o formulário
**Então** um email com o assunto "ISUS APP - DÚVIDA SOBRE O ELMO. DD/MM/AAAA HH:MM:SS" deve ser enviado. E o remetente deve ser o email enviado pelo usuário

- [x] **Dado que** abro a caixa de entrada do feedback.isus@esp.ce.gov.br 
**Quando** pesquiso "Denúncias sobre o Elmo"
**Então** Posso ver os alertas enviados pelos usuários

# Observações

Modelo do json enviado à api:

```json
{
    "duvida": "string",
    "email": "string",
    "versaoAplicativo": "string",
    "plataforma": "string"
  }
```

Essa tarefa está relacionada à #411

**Comment by ruigmoreno** [comment]
Foi verificado que há um erro ao enviar uma dúvida com e-mail válido e descrição da dúvida válida e todas as outras condições de pleno funcionamento do aplicativo.


### Tela do Bug

![photo_2021-01-22_16-27-04](https://user-images.githubusercontent.com/25174912/106042504-e742d600-60bb-11eb-8909-6acc1d7f58f5.jpg)

**Comment by ruigmoreno** [comment]
O bug foi resolvido fazendo a atualização da API iSUS de produção.
