### ISSUE TITLE
Criar Robô Perseverance landing (On-board camera view) para realizar o processo de onboarding de novas pessoas no time iSUS Discovery

### ISSUE THREAD

**Issue by luisfcosta2015** [EscolaDeSaudePublica/isus-api#157]
## **Objetivo**

**Como** Time do iSUS Discovery  
**Quero** realizar o processo  de onboarding  de novas pessoas no time 
**Para** acolher e receber de forma satisfatória as novas pessoas
## **Contexto**
- Sabendo que o processo de chegada de novas pessoas a um time de desenvolvimento, muitas vezes é um processo de exploração num mundo desconhecido e fazendo uma analogia com o robô da nasa chamado-se [Perserevance](https://www.youtube.com/watch?v=5iC3OxAEqco&feature=emb_logo) precisamos implementar um processo de onboarding para pessoas novas que chegam para compor o Time do ISUS Discovery, apresentando todos os conceitos básicos de trabalho, tecnologias, métodos ágeis, código de conduta, papéis de membros, desenvolvimento de código colaborativo e demais informações necessárias para inserir de forma satisfatória novas pessoas ao time, sem que isto cause impacto na rotina do Time e também que seja um processo educacional apoiado por elementos humanos e não humanos no processo.
-

## **Escopo**

- [ ] Criar o protótipo do Robô 
- [ ] Mapear conteúdos educacionais dos documentos internos do Time iSUS Discovery
- [ ] Realizar testes com as pessoas recém chegadas

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

# Observações

A chegada de novas pessoas ao Time, permitiu uma reflexão a respeito deste processo. Convergente com esta questão, as duas pessoas recém chegadas, @JefersonNSoares  e @Laysacunha  possuem conhecimentos de bots e de machine learning. Além disso o Time já vinha desenvolvendo um processo que pode ser consultado neste board [aqui](https://github.com/orgs/EscolaDeSaudePublica/projects/41).

ex: Prototipo

**Comment by luisfcosta2015** [comment]
Inicialmente vamos colocar esforços para integrar o robô com o Docusaurus

**Comment by Laysacunha** [comment]
@MayaraMonte @Clarisse1983 fechando a tarefa aqui. Por favor analisem e se ainda for pertinente colocar no board de Desenvolvimento Humano.
