### ISSUE TITLE
Implementar endpoint para retornar projetos por id ou slug

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#16]

**Comment by jacsonp** [comment]
http://demo.wp-api.org/wp-json/wp/v2/
https://developer.wordpress.org/rest-api/

**Comment by jacsonp** [comment]
https://coronavirus.ceara.gov.br/wp-json/wp/v2/project/5358
Onde project é o tipo e 5358 é o ID
Retorna:
`{"id":5358,"date":"2020-04-24T16:15:12","date_gmt":"2020-04-24T19:15:12","guid":{"rendered":"https:\/\/coronavirus.ceara.gov.br\/?post_type=project&#038;p=5358"},"modified":"2020-04-24T16:15:12","modified_gmt":"2020-04-24T19:15:12","slug":"webconferencia-discute-gestao-da-clinica-e-processo-de-trabalho","status":"publish","type":"project","link":"https:\/\/coronavirus.ceara.gov.br\/project\/webconferencia-discute-gestao-da-clinica-e-processo-de-trabalho\/","title":{"rendered":"Webconfer\u00eancia discute Gest\u00e3o da Cl\u00ednica e Processo de Trabalho"},"content":{"rendered":"<p>Nesta webconfer\u00eancia realizada pela Escola de Sa\u00fade P\u00fablica do Cear\u00e1 no \u00faltimo dia 14 de abril, o M\u00e9dico de Fam\u00edlia e Comunidade, Marco T\u00falio, debateu alguns dos principais pontos da Gest\u00e3o da Cl\u00ednica e Processo de Trabalho em cen\u00e1rio de crise e com foco na pandemia do Coronav\u00edrus (Covid-19).<\/p>\n<p><iframe title=\"Gest\u00e3o da Cl\u00ednica e Processo de Trabalho em Cen\u00e1rio de Crise:Enfrentamento da Pandemia do Covid-19\" width=\"1080\" height=\"608\" src=\"https:\/\/www.youtube.com\/embed\/zmBsBW2rCSU?start=5&#038;feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen><\/iframe><\/p>\n","protected":false},"excerpt":{"rendered":"<p>Nesta webconfer\u00eancia realizada pela Escola de Sa\u00fade P\u00fablica do Cear\u00e1 no \u00faltimo dia 14 de abril, o M\u00e9dico de Fam\u00edlia e Comunidade, Marco T\u00falio, debateu alguns dos principais pontos da Gest\u00e3o da Cl\u00ednica e Processo de Trabalho em cen\u00e1rio de crise e com foco na pandemia do Coronav\u00edrus (Covid-19).<\/p>\n","protected":false},"author":17,"featured_media":5361,"comment_status":"open","ping_status":"closed","template":"","meta":{"_et_pb_use_builder":"","_et_pb_old_content":"","_et_gb_content_width":""},"project_category":[5],"project_tag":[16,19,325,469,470,20],"_links":{"self":[{"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project\/5358"}],"collection":[{"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project"}],"about":[{"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/types\/project"}],"author":[{"embeddable":true,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/users\/17"}],"replies":[{"embeddable":true,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/comments?post=5358"}],"version-history":[{"count":1,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project\/5358\/revisions"}],"predecessor-version":[{"id":5360,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project\/5358\/revisions\/5360"}],"wp:featuredmedia":[{"embeddable":true,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/media\/5361"}],"wp:attachment":[{"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/media?parent=5358"}],"wp:term":[{"taxonomy":"project_category","embeddable":true,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project_category?post=5358"},{"taxonomy":"project_tag","embeddable":true,"href":"https:\/\/coronavirus.ceara.gov.br\/wp-json\/wp\/v2\/project_tag?post=5358"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}`

**Comment by jacsonp** [comment]
https://coronavirus.ceara.gov.br/wp-json/wp/v2/project?slug=webconferencia-discute-gestao-da-clinica-e-processo-de-trabalho
Onde project é o post_type e webconferencia-discute-gestao-da-clinica-e-processo-de-trabalho é o slug
Mesmo retorno da anterior
