### ISSUE TITLE
API iSUS não está captando todos os dados do JSON Wordpress

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/isus-api#184]
# Descrição
Os dados apresentados na tela do iSUS não correspondem a todas as entradas disponíveis no [JSON do Wordpress](https://coronavirus.ceara.gov.br/wp-json/wp/v2/project)

# Passo-a-passo para replicar
1. Execuar o JSON WP
2. Executar iSUS produção
3. Verificar conteúdos de [categorias mapeadas](https://docs.google.com/spreadsheets/d/1CqqiVEWH-YchqFSTlx3NN5zG7RBpvPRUkGo_CCyLThw/edit#gid=0)
4. Comparar conteúdos do JSON com os exeibidos no app

# Ideia de solução

1. Rever a configuração e a [documentação](https://laravel.com/docs/8.x/scheduling) do site oficial do **Laravel**.
2. Pesquisar como outras pessoas fazem o gerenciamento de _jobs_ periódicos no **Larabel**.
3. Verificar na rota correspondente se existe alguma alteração a ser feita.

# Critérios de Aceitação

- [x] Conteúdo integrado
**Dado que** acesso o iSUS  
**Quando** acesso alguma tela de conteúdo integrado via API
**então** devo visualizar os mesmos conteúdos disponíveis no JSON WP

# Observações

> Bug detectado na versão 3.20.8
> O Bub estava na api e não no app.

**Comment by ericsonmoreira** [comment]
O que foi verificado: 

1. A **api** não estava retornando as postagens ordenadas de forma decrescentes pela data de criação da postagem. Isso foi solucionado com uma ordenação feita no final do retorno da rota na api.
2. Posteriormente, verificamos que faltava uma configuração adicional à implementação que tem no código da ai referente ao gerenciamento dos jobs periódicos. Vide [documentação do Laravel](https://laravel.com/docs/8.x/scheduling#running-the-scheduler). 

> Para dimunir fututos problemas, vou add um arquivo com um tutotial de como se fazer essa configuração.

**Comment by ericsonmoreira** [comment]
Tutorial da sincronização com wordpress: 

[https://app.zenhub.com/files/247794672/a2946ce6-1492-45d7-bf7c-7675f7ee5553/download](https://app.zenhub.com/files/247794672/a2946ce6-1492-45d7-bf7c-7675f7ee5553/download)
