### ISSUE TITLE
Adicionar banner do Cisec

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-api#191]
Adicionar banner com o link para o Sisec dentro do iSUS.

**Comment by Laysacunha** [comment]
Segue link da imagem do banner: https://coronavirus.ceara.gov.br/wp-content/uploads/2022/01/Cisec-1.png
Banner deve direcionar para: https://cisec.esp.ce.gov.br/#

**Comment by JefersonNSoares** [comment]
Adicionado banner Cisec homologação e produção.
