### ISSUE TITLE
Fazer tratamento de erro na sincronização com wordpress

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-api#193]
# Contexto

Existe uma sincronização automática dos dados do wordpress (coronavirus) que ocorre a cada 4h. Caso o site do coronavirus esteja fora do ar e essa requisição retorne vazia, a api vai realizar a sincronização e limpar todos os dados (armazenar o que recebeu de retorno). Esse comportamento reflete no app, que fica sem informações para exibir. Dessa forma, faz-se necessário realizar um tratamento de erros para que a sincronização não aconteça caso a requisição retorne vazia, preservando assim, os dados da última sincronização. 

# Escopo

- Realizar tratamento de erro caso sincronização retorne vazio, de forma a preservar dados da última sincronização.
- Encontrar uma maneira para que a api avise quando um erro na sincronização aconteça.

# Critérios de Aceitação

- [x] Tratamento de erro 
**Dado que** ocorra uma sincronização aconteça
**Quando** um erro acontecer durante a sincronização
**Então** os dados da última sincronização são preservados

- [x] `Feedback` de erro
**Dado que** ocorra uma sincronização aconteça
**Quando** um erro acontecer durante a sincronização
**Então** esse erro deve ser informado de alguma forma

> OBS.: Não temos definição ainda de como esse feedback deve ocorrer. Buscar alternativas para essa implementação.

**Comment by ericsonmoreira** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-api/193?planning-poker) with ZenHub @fpontef
