### ISSUE TITLE
Criar endpoints para a funcionalidade registro de frequência das Residências 

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-api#197]
# Objetivo

**Como** pessoa desenvolvedora
**Quero** criar endpoints para a funcionalidade registro de frequencia 
**Para** enviar dados do app para api.

# Contexto

O app tem a funcionalidade de marcar presença de um residente, e essas informações ficarão armazenadas na `api`. Para isso, faz-se necessário criar um conjunto de rotas.

# Escopo

- [x] criar rota de marcar presença do usuario
- [x] criar rota para listar ofertas do Sagu
- [x] criar rota para inserção/atualização das informações de usuário ligadas ao Sagu
- [x] criar rota para buscar informações de usuário ligadas ao Sagu
- [x] criar rota para o relatório geral
- [x] criar rota para listar presenças de um usuário

Especificações de cada rota:
![image](https://user-images.githubusercontent.com/20958122/155382854-4a6b2e89-a925-4b01-9d43-4a3990d9ad6a.png)

# Observações:

- Para a rota de marcar presenças do usuário é necessário enviar também as informações da rota de update UserSaguInfo.

- O relatório geral deve entregar as seguintes informações:
Relatório de Frequência RESMULT 

### Informações gerais
 
1. nome da residência
2. nome do módulo
3. CH do módulo

### Informações residente

1. nome do residente
2. componente
3. programa_residencia
4. municipio_residencia
5. CH presença
6. percentual de presença
7. percentual de falta

OBS: Cada turno de presença deve contabilizar 6h. Logo, num a oferta de 2 semanas, por exemplo, temos 20 turnos e uma disciplina de 120h.

**Comment by ericsonmoreira** [comment]
> Obs.: Faltando apenas a rota de relatório de frequências. Vamos deixar para a próxima sprint por motivos estratégicos.

**Comment by ericsonmoreira** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-api/197?planning-poker) with ZenHub @fpontef
