### ISSUE TITLE
Relatório de informações dos usuários do iSUS para gestão de narrativas

### ISSUE THREAD

**Issue by Laysacunha** [EscolaDeSaudePublica/isus-api#209]
# Objetivo

**Como** pessoa do time de gestão de narrativas
**Quero** informações específicas de usuários do iSUS
**Para** realizar envio de enquete para os usuários

# Contexto

- O time de gestão de narrativas, do Felicilab, está desenvolvendo uma enquete, a ser respondida pelas pessoas usuárias do iSUS, com o intuito de identificar quais são as principais fontes de informação profissionais acessadas por médicos, enfermeiros e fisioterapeutas.

# Escopo

- [ ] realizar consulta no banco de produção com as seguintes informações: nome, sobrenome, e-mail, telefone, categoria e especialidade para todos os profissionais com categoria medicina, fisioterapia e enfermagem. Retornar os dados em planilha ou similar.

**Comment by ericsonmoreira** [comment]
Consulta realizada e arquivos enviados para email da @Laysacunha.

```SQL
SELECT 
  users.name AS "Usuário", 
  users.email AS "Email",
  users.cpf AS "CPF",
  users.telefone AS "Telefone",
  categorias_profissionais.nome AS "Cat. Profissional"
  especialidades.nome AS "Especialidade"
FROM `users` 
INNER JOIN users_especialidades ON users_especialidades.user_id = users.id
INNER JOIN especialidades ON especialidades.id = users_especialidades.especialidade_id
INNER JOIN categorias_profissionais ON categorias_profissionais.id = users.categoriaprofissional_id
WHERE categorias_profissionais.id = 1 OR categorias_profissionais.id = 2 OR categorias_profissionais.id = 3
```

**Comment by ericsonmoreira** [comment]
Um pequeno adendo para consulta dos Fisioterapeutas 

```SQL
SELECT 
  users.name AS "Usuário", 
  users.email AS "Email",
  users.cpf AS "CPF",
  users.telefone AS "Telefone",
  categorias_profissionais.nome AS "Cat. Profissional"
FROM `users` 
INNER JOIN categorias_profissionais ON categorias_profissionais.id = users.categoriaprofissional_id
WHERE  categorias_profissionais.id = 2
```
