### ISSUE TITLE
Ajustar SMTP nos ambientes de produção e homologação do iSUS-api

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-api#222]
# 🚀 Objetivo

**Como** pessoa desenvolvedora
**Quero** garantir que o SMTP esteja funcionado corretamente
**Para** o envio de emails esteja funcionando

## Contexto

Atualizar o SMTP nos ambientes de produção e homologação.

## Escopo

- [ ] Ajustar configuração nas variáveis de ambiente para o SMTP

## Fora de Escopo

- Implementação de novas `features`.

## Critérios de Aceitação

"Melhorar aqui"

## Observação

Código alterado na API de homologação

```bash
class KeycloakService
             $this->getIdKeycloakFromHeader($resposta)
         );

-        $this->enviarEmailCadastro($user);
+        //$this->enviarEmailCadastro($user);

         return $user;
     }
```

**Comment by ericsonmoreira** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/iSUS---Dev-616733cf0d2aa30018f58088/issues/EscolaDeSaudePublica/isus-api/222?planning-poker) with ZenHub @fpontef @Laysacunha

**Comment by victorMagalhaesPacheco** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/isus-api/222?planning-poker) with ZenHub @Junior-Shyko
