### ISSUE TITLE
Ajustes na rota PUT de usuário

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-api#225]
# 🚀 Objetivo

**Como** pessoa desenvolvedora
**Quero** enviar as informações para complementação do cadastro de um usuário
**Para** que a complementação do cadastro de um usuário esteja de acordo com as novas regras o idSaude

## Contexto

Recentemente tivemos mudanças nas regras de negócio do `idSause` com relação ao cadastro de novos usuários. Agora, é necessário informar o CPF no preenchimento do formulário de cadastro do `idSaúde`.

Faz-se necessário providenciar ajustar no `iSUS` também. Essa issue trata do ajuste que devemos fazer para que a rota PUT `/user` não necessite mais o campo cpf como obrigatório. Já que essa informação deve ser obtida pelo idSaude. 

## Escopo

- [ ] Remover a obrigatoriedade de envio de CPF nos dados enviados para atualização de informações de um usuário.

## Fora de Escopo

- Implementação de novas `features`.

## Critérios de Aceitação

- [ ] Remover validação de CPF na rota PUT `/user`
      **Dado que** envie uma request válida para a rota da api do iSUS PUT `/user` 
      **Quando** essa request chegar na api
      **então** o campo e CPF não deverá estar sendo usando para validar as informações

**Comment by victorMagalhaesPacheco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/isus-api/225?planning-poker) with ZenHub @ericsonmoreira @fpontef
