### ISSUE TITLE
Ajustar criação de usuário no iSUS

### ISSUE THREAD

**Issue by ericsonmoreira** [EscolaDeSaudePublica/isus-api#228]
# Objetivo

**Como** pessoa usuária do iSUS  
**Quero** poder me cadastrar 
**Para** usando o meu idSaude

## Contexto

Recentemente tivemos mudanças nas regras de negócio do `idSause` com relação ao cadastro de novos usuários. Agora, é necessário informar o CPF no preenchimento do formulário de cadastro do `idSaúde`.

Faz-se necessário providenciar ajustar no `iSUS` também. Essa tarefa trata de ajustes no momento da criação de um usuário no iSUS. Agora, precisamos salvar na nossa base de dados o CPF que vem do idSaude. Como no idSaude o campo que contem a informação do CPF agora é o username, precisamos coletar o username que vem como retorno do idSaude para salvar no campo cpf de um novo usuário do iSUS. 

## Escopo

- [ ] Alterar o procedimento de criação de usuário.

## Fora de Escopo

- Implementação de novas `features`.

## Critérios de Aceitação

- [ ] Criação de um novo usuário
      **Dado que** um novo usuário está sendo criado
      **Quando** a api for salvar as informações desse novo usuário
      **então** o campo CPF deve ser preenchido com a informação do username que vem da api do idSaude

**Comment by ricardopoppi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/isus-api/228?planning-poker) with ZenHub @ericsonmoreira @Laysacunha @fpontef

**Comment by ricardopoppi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/isus-api/228?planning-poker) with ZenHub @Junior-Shyko
