### ISSUE TITLE
Adicionar Banner Arboviroses

### ISSUE THREAD

**Issue by fpontef** [EscolaDeSaudePublica/isus-api#240]
## 🚀 Objetivo

**Como** pessoa da comunicação da ESP
**Quero** adicionar banner sobre Arboviroses
**Para** ampliar alcance da informação

## Contexto

- Foi solicitado a inserção do banner do **Arboviroses**. Solicitação realizada por Ariane Cajazeiras via email da ascom.
- Solicitou retirada do banner `Guia da Diversidade`, inserção do novo banner `Arboviroses` na posição 1, antes do banner `Livro`, mantendo a ordem dos demais.

Link da [imagem](http://www.esp.ce.gov.br/wp-content/uploads/sites/78/2022/07/Arboviroses-no-Ceara.png).

O caminho a ser direcionado é para o roteamento interno do componente `Arboviroses` no próprio iSUS.

## Escopo

- [x] Adicionar banner do **Arboviroses** 
- [ ] Remover Banner Guia da Diversidade

# Critérios de Aceitação

- [ ] Visualização de banner
**Dado que** estou no iSUS
**Quando** acesso a Home 
**Então** visualizo o banner do **Arboviroses** na ordem 1.

- [ ] Direcionamento do banner
**Dado que** estou vendo as lista de banners
**Quando** clico no banner **Arboviroses**
**Então** sou redirecionado para o componente

# Observações

- Imagem do banner: http://www.esp.ce.gov.br/wp-content/uploads/sites/78/2022/07/Arboviroses-no-Ceara.png
- Link de direcionamento do banner: Componente interno `Arboviroses` do iSUS
- Ordem do banner: 1

- O banner será ativado somente após lançamento do app nas lojas.

**Comment by fpontef** [comment]
Banner já adicionado como inativo no banco de dados, aguardando somente o lançamento da nova versão do app.

**Comment by ericsonmoreira** [comment]
@fpontef Já mandei novamente o app versão 3.22.4 para revisão na app store.
