### ISSUE TITLE
Adicionar SWAGGER na API

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#41]
## **Contexto**
Implementar o swagger para que possamos ter uma documentação das APIs do projeto.

## **Entrega esperada**
Swagger com as APIs desenvolvidas do projeto.

## **Resultado**
Swagger implementado com inclusão das APIs automáticas conforme são criadas no projeto.

**Comment by kurjes** [comment]
@victorMagalhaesPacheco adicionar mais contexto para que possamos priorizar junto ao @uira

**Comment by victorMagalhaesPacheco** [comment]
Necessário realizar mapeamento de rotas, parâmetros, corpo e verbos http para mapeamento de endpoints já existentes.

**Comment by victorMagalhaesPacheco** [comment]
Link para a documentação momentânea no ambiente de homologação: http://apiisus.dev.org.br/api/documentation
