### ISSUE TITLE
Adicionar campo na imagem API.

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#42]

**Comment by caetanooliveira** [comment]
Objetivo:
Permitir ser anexada imagem no email de feedback

Contexto:
Hoje a api só permite enviar os campos de tipo de feedback, texto e email. Agora precisamos adicionar imagem.

**Temos que definir limites de tamanho e formatos aceitos
Entender que normalmente é um print do celular.**

Alcance:
ios e android

AC:
Dado que o usuário enviou tipo, email e texto
Quando a api recebe esses contaúdos
Feedback é enviado com sucesso à ESP

Dado que o usuário está na tela de feedback
Quando clica no adicionar imagem
O app pede permissão de acesso à galeria
E abre sua galeria de fotos

Dado que o usuário não preencheu tipo, email ou texto
Quando ele envia uma feedback
A api retorna um erro ao front

Dado que o usuário preencheu tipo, email, texto e imagem
Quando ele clica botão enviar
Feedback é enviado com sucesso à ESP

Dado que abro a caixa de entrada da ESP
Quando o feedback tem imagem
Posso fazer download e abri-la.

**Comment by matheusbernardes19** [comment]
> Atualmente o tamanho padrão é de 2MB, mas podemos aumentar!
> O formato acredito que .png, .jpg, .jpeg
> Faz sentido?

Segui esse padrão na validação da imagem: 2MB máximo e formatos apenas .png, .jpg e .jpeg
