### ISSUE TITLE
Adicionar novos campos no endpoint de projetos para retornar anexos

### ISSUE THREAD

**Issue by caetanooliveira** [EscolaDeSaudePublica/isus-api#47]
**Objetivo**
Permitir anexos de notas e artigos ficarem disponíveis offline.

**Contexto**
Atualmente o 'endpoint' do projeto, retorna em seu escopo no 'content' os links para acesso aos pdfs, o que torna adicionar mais complexidade na quebra do conteúdo para realizar a extração dos links. O que acontece é que esses pdfs muitas vezes tem outros pdfs ou links no seu corpo, o  objetivo desse card é que quando o usuario baixe o artigo para tê-lo offline, ele tenha não só o artigo mas todos os outros documentos referenciados naquele artigo.

**Nota:** 
Abaixo segue exemplo de acesso em Educação > Documentos. O artigo poderia ficar offline, mas ele é basicamente um link a um pdf. O objetivo desse card é que o pdf fique disponivel offline tbm, para isso ele precisa ser adicionado no endpoint.
![educacao permanente isus](https://user-images.githubusercontent.com/65370398/85569858-482b9c80-b609-11ea-8720-1ec198831bb5.jpeg)

**Escopo**
Realizar separação dos anexos (pdf) de um projeto em novos campos no endpoint de retorno para o cliente (react native).
Adicionar novos campos de anexos, baseado no 'content' do projeto.

**Critérios**
Dado que o cliente realize uma solicitação HTTP no verbo GET para o projeto passando um 'id'
Retorna mais campos no formato JSON que são os novos anexos
Ao receber os dados de anexo, pode se aplicar toda a regra baseado nos novos campos.

Dado que o cliente solicite download de um artigo
Quando esse artigo tem outros pdfs dentro
Ficam disponíveis tanto o artigo original quanto suas referências.

**Comment by victorMagalhaesPacheco** [comment]
@caetanooliveira fiz a atualização acima do card, se quiser pode editar.

**Comment by caetanooliveira** [comment]
@victorMagalhaesPacheco editei uma parte pro pessoal entender, confirma se acha que fez sentido?

**Comment by jacsonp** [comment]
o parametro de query ?_embed retorna dados as mídias e autores anexados ao post, porem ele só funciona se estiver anexado ao post, caso contrário não vai trazer os dados

**Comment by victorMagalhaesPacheco** [comment]
Examplo: https://coronavirus.ceara.gov.br/wp-json/wp/v2/project/2708 na propriedade 'wp:attachment' retorna https://coronavirus.ceara.gov.br/wp-json/wp/v2/media?parent=2708 como todos os anexos do projeto em objeto.

**Comment by victorMagalhaesPacheco** [comment]
Novo retorno anexos (array)
