### ISSUE TITLE
Criar endpoints para trazer listas de opções para cadastro

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-api#55]
### **Objetivo**
Criar listas para os campos de seleção do cadastro de usuário na API:

### **Escopo**
1- Categoria profissional (utilizado neste MVP)

- Medicina
- Fisioterapia
- Enfermagem
- Terapia Ocupacional
- Farmácia
- Coordenação Clínica
- Coordenação de Enfermagem
- Outra

2- Titulação Acadêmica (seleção)
- Especialista
      - Residência em 
      - Terapia intensiva
      - Clínica médica
      - Urgencia e emergencia
      - Anestesiologia
      - Outra
- Graduação
- Mestrado
- Doutorado

3- unidades de serviço (utilizado neste MVP)
https://drive.google.com/file/d/1Ud5jLWDe30gjZDfnVqf4bgIa243mctUQ/view (lista da esquerda)

4- Tipo de Contratação - (Seleção)
Estatutário
Cooperado
Terceirizado
Autônomo
Outro, qual? (campo livre)

5- Instituição (pode adicionar várias)
- Lista CNES - Victor
- Outra

6- Atuação como docente (opcional) (multipla escolha????) - AGUARDA DEFINIÇÃO
- Não
- Sim
     - Professor ensino superior
     - Preceptor em serviço
     - Outro

Fonte:
https://docs.google.com/presentation/d/1-AbnLgRmKIoGcKUoEriFnUFY2-OWkc_pspQcN_kOPt4/edit#slide=id.g86a325bfdc_0_20

Protótipo:
https://www.figma.com/file/FLKurtBDSBYAiYcS5xAPYC/iSUS?node-id=1550%3A7606

**Comment by victorMagalhaesPacheco** [comment]
Endpoints para o formulário @amaurymeireles :

- https://apiisus.inova.esp.br/api/categorias-profissionais
- https://apiisus.inova.esp.br/api/instituicoes
- https://apiisus.inova.esp.br/api/tipos-contratacoes
- https://apiisus.inova.esp.br/api/titulacoes-academica
- https://apiisus.inova.esp.br/api/estados/{ID_ESTADO}/municipios
- https://apiisus.inova.esp.br/api/estados
