### ISSUE TITLE
Criar endpoint para realizar o login na API

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/isus-api#56]
# Objetivo
**Eu como** Profissional de saúde
**Eu Quero** realizar o login no aplicativo
**Para que** eu possa ter acesso às informações registradas e conteúdo personalizado

# Contexto
Para que o app possa efetuar o login no aplicativo, é importante implementar os endpoints de autenticação na API do iSUS. Ela deverá se comunicar com o keycloak e realizar a requisição.

# Escopo

- [x] Realizar a integração com Keycloak.
- [x] Criar um endpoint de login que recebe o e-mail e a senha e verifica se o usuário existe
- [x] Caso algum dos dados do usuário esteja incorreto, o servidor deve informar uma mensagem de erro informando que a há dados incorretos.
- [x] Caso os dados estejam corretos, o servidor deve informar uma mensagem de sucesso junto com o token do usuário. 
- [x] Criar endpoint de logout

# Critério de aceitação
- [x] login no Keycloak realizado com sucesso através da API

**Comment by mbernardes19** [comment]
@ilizakoski  @ItaloRod 

**Endpoint para o realizar o login**:
`POST https://apiisus.inova.esp.br/api/auth`
**Campos**:
`email`: String (obrigatório)
`senha`: String (obrigatório)

**Endpoint para o realizar o logout**:
`POST https://apiisus.inova.esp.br/api/logout`
*Esse endpoint é protegido, precisa passar o access_token que vem na resposta da requisição de login no Header `Authorization`*

**Campos**:
`refresh_token`: String (refresh_token que vem na resposta da requisição de login)
