### ISSUE TITLE
Criar cadastro de usuário com dados fixos

### ISSUE THREAD

**Issue by laurapmelo** [EscolaDeSaudePublica/isus-api#57]
### **Objetivo**
Criar um cadastro fictício com dados fixos para validar integração com keycloack.

### **Contexto**
Antes de criar as telas de cadastro, precisamos configurar o keycloack para receber os campos previstos. Para isso, vamos criar um login através de dados fixos no backend validando a integração.

**Campos para cadastro**
Nome completo: Laura Panceri Melo
Email: laura@laura.com
Senha: Laura@123
Telefone: (51) 99999-9999
CPF: 012.345.567-89
Município de residência: Fortaleza
Categoria profissional: medicina
Unidade/Serviço em que atua: Terapia Intensiva
Titulação acadêmica: Especialista
Titulação acadêmica 2: Mestrado
Tipo de contratação 1: Estatutário
Tipo de contratação 2: Cooperado
Instituição 1: Hospital geral fortaleza
Atuação como docente: professor ensino superior
Concordo com os termos? sim

Campos obrigatórios:
- Nome completo
- Email
- Telefone
- CPF
- Município de residência

Fonte de campos do cadastro:
https://docs.google.com/presentation/d/1-AbnLgRmKIoGcKUoEriFnUFY2-OWkc_pspQcN_kOPt4/edit?usp=sharing

### **Critério de aceitação**
- [x] cadastro criado com dados descritos acima (verificar através do navegador)
- [x] Adicionar ao ```.env``` os seguintes campos com seus respectivos valores:

````.env
KEYCLOAK_URL=
KEYCLOAK_REALM=
KEYCLOAK_CLIENT_ID=
KEYCLOAK_REDIRECT_URI=
KEYCLOAK_APPSITE_URI= 
````
- [x] Adicionar no ```.env.example``` os seguintes campos com estes valores:

````.env
KEYCLOAK_URL=keyCloarkUrl
KEYCLOAK_REALM=keyCloakRealm
KEYCLOAK_CLIENT_ID=keyCloakClientId
KEYCLOAK_REDIRECT_URI=keyCloadRedirectUri
KEYCLOAK_APPSITE_URI=keyCloadkAppsiteUri
````

**Comment by mbernardes19** [comment]
Melhorias que podem ser feitas após finalização deste card:
- Criar mensagens de erros para casos mais específicos (sem conexão com internet, servidor com problema, campo faltando etc)
- Guardar token em cache após primeira autenticação

**Comment by mbernardes19** [comment]
Endpoint para o realizar o cadastro @amaurymeireles @ItaloRod:

`POST https://apiisus.inova.esp.br/api/user`
**Campos:**
`email`: String (obrigatório)
`nome`: String (obrigatório)
`sobrenome`: String (obrigatório)
`senha`: String (obrigatório)
`repetirsenha`: String (obrigatório)
`telefone`: String (obrigatório)
`cpf`: String (obrigatório tamanho=11, somente números)
`cidadeId`: Number (obrigatório)
`cidade`: String (obrigatório)
`termos`: Boolean (obrigatório)
`estadoId`: Number
`estado`: String
`categoriaProfissional`: JSON.stringify([{}, {} ...])
`titulacaoAcademica`: JSON.stringify([{}, {} ...])
`tipoContratacao`: JSON.stringify([{}, {} ...])
`instituicao`: JSON.stringify([{}, {} ...])
`unidadeServico`: JSON.stringify([{}, {} ...])

**Comment by mbernardes19** [comment]
Endpoint para o realizar o cadastro @amaurymeireles @nicoledbianchin @ilizakoski @lemenezes @kurjes @ItaloRod:

`POST https://apiisus.inova.esp.br/api/user`
**Campos:**
`email`: String (obrigatório)
`nome`: String (obrigatório)
`sobrenome`: String (obrigatório)
`senha`: String (obrigatório)
`repetirsenha`: String (obrigatório)
`telefone`: String (obrigatório)
`cpf`: String (obrigatório tamanho=11, somente números)
`cidadeId`: Number (obrigatório)
`cidade`: String (obrigatório)
`termos`: Boolean (obrigatório)
`estadoId`: Number
`estado`: String
`categoriaProfissional`: JSON.stringify([{}, {} ...])
`titulacaoAcademica`: JSON.stringify([{}, {} ...])
`tipoContratacao`: JSON.stringify([{}, {} ...])
`instituicao`: JSON.stringify([{}, {} ...])
`unidadeServico`: JSON.stringify([{}, {} ...])
