### ISSUE TITLE
Criar endpoint para excluir usuário

### ISSUE THREAD

**Issue by mbernardes19** [EscolaDeSaudePublica/isus-api#64]
## Contexto
Neste momento, quando um usuário é cadastrado no iSUS, é criado simultaneamente um usuário no Keycloak e um no banco de dados da API do iSUS para manter registro dos dados desse usuário nesses dois escopos.

Porém ainda não existe uma forma de excluir o usuário nos dois escopos ao mesmo tempo, podem surgir bugs devido a essa falta de sincronia quando alguém for administrar esses usuários ou caso um usuário possa excluir o seu cadastro no futuro.

**Comment by uira** [comment]
@mbernardes19 Na verdade,  esse comportamento é exatamente o esperado.

Eles estão integrados, e um está criando o outro, mas são serviços diferentes, inclusive, com termos de uso e papéis diferentes.

Mas acho que essa demanda levantada faz sentido, no ponto de vista da usabilidade, considerando uma hipótese possível, em que o usuário queira deletar/remover/excluir contas em vários serviços ao mesmo tempo.

**Comment by kurjes** [comment]
Intender com @uira prioridade desse card
