### ISSUE TITLE
criação das macro-categorias no wordpress para home personalizada 

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-api#71]
### **Objetivo**
Criar macro-categorias relacionadas aos serviços do profissional de saúde no wordpress, para que possamos segmentar o nosso conteúdo a partir delas.

### **Contexto**
Queremos criar uma home com conteúdo personalizado para o usuário de acordo com os serviços que ele atua, para que seja possível é necessário que o conteúdo do wordpress seja filtrado. Esses posts serão filtrados de acordo com [essa tabela](https://docs.google.com/spreadsheets/d/1Ud5jLWDe30gjZDfnVqf4bgIa243mctUQ/edit#gid=1922492045), onde as macro-categorias estão na coluna "E" e os serviços que o profissional atual na coluna "D", como visto na tabela as macro-categorias agrupam os serviços.

**Comment by ItaloRod** [comment]
colocamos as macro-categorias e atribuímos a uma categoria principal chamada ISUS. Porém os conteúdos disponibilizados serão somente relacionados as macro-categorias? Por exemplo, um usuário que escolheu UTI, também receberá conteúdo de pronto-socorro, por fazer parte da mesma macro-categoria?

**Comment by kurjes** [comment]
> colocamos as macro-categorias e atribuímos a uma categoria principal chamada ISUS. Porém os conteúdos disponibilizados serão somente relacionados as macro-categorias? Por exemplo, um usuário que escolheu UTI, também receberá conteúdo de pronto-socorro, por fazer parte da mesma macro-categoria?

Sim Italo, decidimos usar essas macro-categorias porque fica mais simples para o pessoal da ASCOM categorizar os posts. O entendimento é esse mesmo que vc teve.
