### ISSUE TITLE
Criação de endpoints com filtros para home personalizada

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-api#72]
## **Objetivo**
Criar endpoints para que retornem conteúdos de Educação e Pesquisa que estejam ligados ao serviços que a usuária atua, a partir  desses conteúdos criaremos uma home personalizada para a usuária quando a mesma estiver logada no app. 

## **Contexto**
Na tarefa #71 foram criadas no wordpress macro-categorias que serão usadas para segmentar o conteúdo do site, queremos que nossa API faça a relação entre essas macro-categorias e os serviços que o profissional de saúde atua de acordo com [essa planilha](https://docs.google.com/spreadsheets/d/1Ud5jLWDe30gjZDfnVqf4bgIa243mctUQ/edit#gid=1922492045). E que sejam disponibilizado esses endpoints para que possamos criar sessões de Educação e Pesquisa de acordo com o perfil de cada usuária, em sua home quando ela estiver logada.

**Comment by victorMagalhaesPacheco** [comment]
Atividade finalizada e enviada pro ambiente de homologação.
