### ISSUE TITLE
criar endpoint para trazer dados do perfil

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-api#77]
### **Objetivo**
Atualmente estamos pegando os dados de perfil de um JWT no keyclock. Queremos mudar para trazer esses dados da API, queremos trazer os dados pessoais e profissionais que são informados durante o cadastro.

### **Escopo**

- [ ]  campo de nome 

- [ ]  campo de email

- [ ]  campo de telefone

- [ ]  campo de cpf

- [ ]  campo de município 

- [ ]  campo de categorias em que o profissional atua 

- [ ]  campo de setor onde o profissional atua

**Comment by victorMagalhaesPacheco** [comment]
@kurjes Esse card já está sendo representado por esse: https://github.com/EscolaDeSaudePublica/isus-api/issues/76
