### ISSUE TITLE
criar endpoint para editar informações profissionais

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-api#78]
### **Objetivo**
Os campos de informação profissionais não são obrigatório para o usuário durante o nosso  cadastro, queremos que o  usuário seja capaz de inserir os dados caso não tenha feito, logo é necessário um endpoint de edição. 

### **Escopo**
- [x]  campo de categorias em que o profissional atua 

- [x]  campo de setor onde o profissional atua

**Comment by victorMagalhaesPacheco** [comment]
Solicitação para: 
URL: /api/user
Verbo HTTP: PUT
Header: Authorization: Bearer {{TOKEN_DO_USUARIO_LOGADO}}

Dados JSON parâmetros
```json
{
	"email": "EMAIL DO USUÁRIO",
	"nomeCompleto": "NOME COMPLETO",
	"telefone": "TELEFONE",
	"cpf": "CPF DO USUÁRIO",
	"rg": "RG DO USUÁRIO",
	"cidadeId": "ID CIDADE",
	"cidade": "NOME CIDADE",
	"termos": true,
	"categoriaProfissional": "{\"id\":1,\"nome\":\"Medicina 1\"}",
	"titulacaoAcademica": "[{\"id\":1,\"nome\":\"Graduado\"},{\"id\":2,\"nome\":\"Especialista\"}]",
	"tipoContratacao": "[{\"id\":1,\"nome\":\"Estatutário\"},{\"id\":2,\"nome\":\"Cooperado\"}]",
	"unidadeServico": "[{\"id\":5,\"nome\":\"Pronto-socorro\"},{\"id\":6,\"nome\":\"Ambulatório\"}]"
} 
`

Processo muito parecido com o do cadastro, entretanto sem passar senhas.

**Comment by ericsonmoreira** [comment]
Funcionalidade já implementada em #288.
