### ISSUE TITLE
Enviar email de boas vindas para o profissional cadastrado

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#84]
### **Contexto**
Ao realizar o cadastro do profissional no aplicativo, automaticamente enviar um email para o profissional.

### **Objetivo**
**Eu como** profissional da saúde
**Quero** realizar o cadastro no aplicativo e no fim do processo receber um email de confirmação de cadastro
**Para** para receber a confirmação de cadastro

**Comment by Clarisse1983** [comment]
Aqui está o texto do email: https://docs.google.com/document/d/1x1_O5XzDVy7_fTyQo-U0lfqmsROXKgpDvZLgDEdKNIA/edit?ts=5f5fc604

**Comment by victorMagalhaesPacheco** [comment]
Layout do e-mail de boas vindas no momento: 
![Captura de tela de 2020-09-16 12-28-02](https://user-images.githubusercontent.com/3487411/93358758-417f8080-f818-11ea-8012-e6b5552eac4c.png)

**Comment by Clarisse1983** [comment]
Achei massa! Mas sou suspeita, rsrs.

*Clarisse Castro Cavalcante*
Jornalista pela Universidade Federal do Piauí.
Especialista em Teorias da Comunicação e da Imagem pela Universidade
Federal do Ceará.
Mestre e Doutora em Informação e Comunicação em Saúde pela Fundação Oswaldo
Cruz (RJ).
Skype: clarisse.castro3
32. 991586986




Em qua., 16 de set. de 2020 às 12:30, Victor Magalhães Pacheco <
notifications@github.com> escreveu:
