### ISSUE TITLE
Token expirado redirecionar para fazer login - 401 HTTP

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#86]
### **Contexto**
Atualmente o token do usuário expira depois de um determinado tempo "x", ao expirar (http 401) usar uma nova rodada de autenticação.

### **Objetivo**
**Eu como**  profissional da saúde
**Quero** realizar o login no aplicativo e após alguns dias sem acessar o aplicativo, acessar o meu perfil e continuar com os meus dados preenchidos.
**Para** consultar o perfil sem perder a sessão

**Comment by kurjes** [comment]
Necessário priorização com @uira

**Comment by daianefreira** [comment]
Issue fechado sem desenvolvimento, pois conforme validação realizada com Italo nao fazia mais sentido. Por problema já ter sido tratado em outra issue.
