### ISSUE TITLE
Adicionar a o campo especialidade ao endpoint de edição de informações profissionais

### ISSUE THREAD

**Issue by kurjes** [EscolaDeSaudePublica/isus-api#92]
## **Objetivo**
Como usuária logada
Quero ter acesso ao meu Perfil
Para adicionar informações profissionais que não forneci durante o cadastro

## **Contexto**
Estamos evoluindo nosso cadastro,  o campo de especialidades caso a usuária seja Enfermeira ou Médica já foi adicionado ao fluxo. Foi visto que esse campo é essencial para que possamos entregar as usuárias  uma home personalizada com conteúdos mais assertivos. Agora é necessário que esse campo também esteja no fluxo de adicionar informações profissionais não cadastradas que temos dentro do perfil. 

## **Escopo**
- [ ] adição do campo especialidade do endpoint

**Comment by Laysacunha** [comment]
essa funcionalidade já está disponível. Foi realizada na issue #314 que já está fechada.
