### ISSUE TITLE
Realizar a troca da branch principal do repositório master -> main (API)

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/isus-api#99]
# Contexto
A partir de agora todas as novas branches padrões  do github se chamarão main no lugar da master para evitar referências à escravidão. 
É importante para o PROJETO e seus repositórios rejeitar quaisquer referências racistas.

https://github.com/github/renaming

**Comment by ItaloRod** [comment]
esse card não faz mais sentido visto que Já foi realizado por parte da API: https://github.com/EscolaDeSaudePublica/isus-api
